android/uamp

- mobile/src/main/java/com/example/android/uamp/ui/FullScreenPlayerActivity.java
- mobile/src/main/res/layout/activity_full_player.xml
imageView1 sounds so lame... :)
> Rename play/pause ImageView

- .google/packaging.yaml
> Remove ChromeCast from metadata

- mobile/build.gradle
- mobile/src/main/java/com/example/android/uamp/MediaNotificationManager.java
- mobile/src/main/java/com/example/android/uamp/ui/BaseActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/FullScreenPlayerActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/MediaBrowserFragment.java
- mobile/src/main/java/com/example/android/uamp/ui/MediaItemViewHolder.java
- mobile/src/main/java/com/example/android/uamp/ui/MusicPlayerActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/PlaybackControlsFragment.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/CardPresenter.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvBrowseActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvBrowseFragment.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvPlaybackActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvPlaybackFragment.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvVerticalGridActivity.java
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvVerticalGridFragment.java
- mobile/src/main/java/com/example/android/uamp/utils/MediaIDHelper.java
- mobile/src/main/java/com/example/android/uamp/utils/QueueHelper.java
- mobile/src/main/res/values/strings.xml
Upgraded to SDK Oreo, updated some libraries and added Notification Channel in order to display notifications in SDK Oreo.
> Upgraded to SDK Oreo.

- mobile/src/main/java/com/example/android/uamp/MediaNotificationManager.java
- mobile/src/main/java/com/example/android/uamp/model/MusicProvider.java
- mobile/src/main/java/com/example/android/uamp/playback/PlaybackManager.java
- mobile/src/main/java/com/example/android/uamp/utils/QueueHelper.java
Minor updates for playing from search as well as some code in MediaNotificationManager.
> Minor updates

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobile/build.gradle
- mobile/src/main/java/com/example/android/uamp/ui/tv/TvPlaybackFragment.java
> Update gradle files

- mobile/src/main/java/com/example/android/uamp/playback/LocalPlayback.java
Replace deprecated constants by new constants of Exoplayer.
> Replace deprecated constants by new constants of Exoplayer.

- mobile/src/main/java/com/example/android/uamp/playback/LocalPlayback.java
Replace deprecated methods by new methods of Exoplayer
> Replace deprecated methods by new methods of Exoplayer

- media/src/main/java/com/example/android/uamp/media/NotificationBuilder.kt
Fix wrong title of notification actions.
> Fix wrong title of notification actions

- common/build.gradle
- common/src/androidTest/java/com/example/android/uamp/media/library/MusicSourceTest.kt
- Added target compatibility 1.8 to common module's build.gradle
- Implemented missing method in TestMediaSource
> Fix for running MediaSourceTest

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_nowplaying.xml
Hi , I ran into some build errors when building this demo , and I fixed them ,now it is OK to build and assemble. And feel free to edit the change.😊
>  fixed some build errors 

- automotive/build.gradle
- automotive/src/main/res/values/strings.xml
Small updates to strings in the sign-in screens.
> Update strings in sign-in screens

- app/src/main/java/com/example/android/uamp/viewmodels/NowPlayingFragmentViewModel.kt
- common/src/main/java/com/example/android/uamp/common/MusicServiceConnection.kt
- common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt
- common/src/main/java/com/example/android/uamp/media/library/BrowseTree.kt
Full write up here: https://github.com/android/uamp/issues/316
> Add check for null media id in the nowPlaying field. Fixes #316.

- common/src/main/java/com/example/android/uamp/media/UampNotificationManager.kt
Fixes #364 
* Checks if a notification channel should be created, if it should, creates the notification channel.
According to the `PlayerNotificationManager` documentation [https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/PlayerNotificationManager.html):
_The caller is responsible for creating the notification channel._
> Fix app crashing if the notification channel has not been created yet

- app/build.gradle
- app/src/main/java/com/example/android/uamp/MediaItemAdapter.kt
- app/src/main/java/com/example/android/uamp/fragments/MediaItemFragment.kt
- app/src/main/java/com/example/android/uamp/fragments/NowPlayingFragment.kt
- app/src/main/java/com/example/android/uamp/viewmodels/NowPlayingFragmentViewModel.kt
- app/src/main/res/layout/fragment_mediaitem_list.xml
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
Hello guys, I refactored fragments, removed all findViewById / synthetic  and introduced ViewBinding according to [this feature request](https://github.com/android/uamp/issues/331)
I'm happy I could contribute to **uamp**!
> #331 refactor regarding viewBinding, update kotlin and gradle plugin

- common/src/main/java/com/example/android/uamp/media/MusicService.kt
- common/src/main/res/values/strings.xml
This commit add support to handle an Exoplayer error.
> #371 added support to exoplayer error handling

- common/src/main/java/com/example/android/uamp/media/UampNotificationManager.kt
- common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt
- common/src/main/java/com/example/android/uamp/media/library/JsonSource.kt
Change the saved art URI to be the remove URI as opposed to a
locally cached resource URI.
> Add art to the Cast receiver app

- common/src/main/java/com/example/android/uamp/media/PackageValidator.kt
- common/src/main/java/com/example/android/uamp/media/library/BrowseTree.kt
To support a more precise meaning and be more inclusive.
> Switch UAMP to use a better named "allow list"

- common/src/main/java/com/example/android/uamp/media/MusicService.kt
- common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt
- common/src/main/java/com/example/android/uamp/media/library/JsonSource.kt
> Fix art display in local device when casting

- automotive/build.gradle
- automotive/src/main/AndroidManifest.xml
- automotive/src/main/res/xml/automotive_app_desc.xml
For the Google Play Store deployment, it's required to have these entries in the AndroidManifest.xml
> Required for PlayStore deployment

- app/build.gradle
- app/src/main/java/com/example/android/uamp/MainActivity.kt
- app/src/main/java/com/example/android/uamp/MediaItemAdapter.kt
- app/src/main/java/com/example/android/uamp/fragments/MediaItemFragment.kt
- app/src/main/java/com/example/android/uamp/fragments/NowPlayingFragment.kt
- app/src/main/java/com/example/android/uamp/viewmodels/MainActivityViewModel.kt
- automotive/src/main/java/com/example/android/uamp/automotive/PinCodeSignInFragment.kt
- automotive/src/main/java/com/example/android/uamp/automotive/SettingsFragment.kt
- automotive/src/main/java/com/example/android/uamp/automotive/SignInActivity.kt
- automotive/src/main/java/com/example/android/uamp/automotive/SignInLandingPageFragment.kt
- automotive/src/main/java/com/example/android/uamp/automotive/UsernameAndPasswordSignInFragment.kt
- automotive/src/main/res/values/strings.xml
- build.gradle
- common/src/main/java/com/example/android/uamp/media/PackageValidator.kt
- Fixes (most) deprecation warnings (aside from those related to
signature checks in PackageValidator)
- Converts a few hard-coded strings into string resources (in
automotive).
> Address warnings

- common/src/main/java/com/example/android/uamp/media/extensions/JavaLangExt.kt
> Simplify `containsCaseInsensitive`

- app/src/main/AndroidManifest.xml
Moved `action.MEDIA_PLAY_FROM_SEARCH` to `MainActivity` from
`MusicService` (Thanks for the hint, @orcunkobal!)
(Hopefully) fixes #381
> Fix for voice commands not working

- README.md
- docs/FAQs.md
> Add FAQs page

- common/src/main/java/com/example/android/uamp/media/PackageValidator.kt
> Allow apps which have a notification listener to control UAMP

- common/src/main/java/com/example/android/uamp/media/MusicService.kt
Make `CastPlayer` nullable and only initialise it if Cast is supported. Fixes #412
> Only enable Cast playback on platforms which support it

- automotive/src/main/java/com/example/android/uamp/automotive/AutomotiveMusicService.kt
- build.gradle
- common/src/main/java/com/example/android/uamp/media/CastMediaItemConverter.kt
- common/src/main/java/com/example/android/uamp/media/MusicService.kt
- common/src/main/java/com/example/android/uamp/media/PackageValidator.kt
- common/src/main/java/com/example/android/uamp/media/PersistentStorage.kt
- common/src/main/java/com/example/android/uamp/media/UampNotificationManager.kt
- common/src/main/java/com/example/android/uamp/media/extensions/MediaMetadataCompatExt.kt
- common/src/main/java/com/example/android/uamp/media/library/AlbumArtContentProvider.kt
- common/src/main/java/com/example/android/uamp/media/library/JsonSource.kt
Upgrades gradle dependency to ExoPlayer version 2.16.0, migrates code and removes deprecations.
> Upgrade to ExoPlayer 2.16.0

- common/src/main/res/xml/allowed_media_browser_callers.xml
Add Android Auto's debug signing key.
> Add Android Auto's debug key to allowed media browser callers.
